//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyAdsBlocker.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpotifyAdsBlocker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Block Banner Ads benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlockBannersCheckboxText {
            get {
                return ResourceManager.GetString("BlockBannersCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You may need to restart Spotify or your computer for this setting to take effect. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlockBannersRestart {
            get {
                return ResourceManager.GetString("BlockBannersRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabling/Disabling this option requires Administrator privileges.
        ///
        ///Please reopen SpotifyAdsBlocker with &quot;Run as Administrator&quot;. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string BlockBannersUAC {
            get {
                return ResourceManager.GetString("BlockBannersUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpotifyAdsBlocker is hidden. Double-click this icon to restore. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HiddenNotify {
            get {
                return ResourceManager.GetString("HiddenNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Блокатор рекламы Spotify скрыт. Дважды щелкните этот значок, чтобы восстановить. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HiddenNotifyRu {
            get {
                return ResourceManager.GetString("HiddenNotifyRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify Reklam Engelleyici gizlenir. Geri yüklemek için bu simgeye çift tıklayın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string HiddenNotifyTr {
            get {
                return ResourceManager.GetString("HiddenNotifyTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify ads will not be muted if SpotifyAdsBlocker is not running.
        ///
        ///Are you sure you want to exit? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OnExitMessageBox {
            get {
                return ResourceManager.GetString("OnExitMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error patching Spotify. SpotifyAdsBlocker may not work. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string PatchErrorMessageBox {
            get {
                return ResourceManager.GetString("PatchErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpotifyAdsBlocker Version: {0}
        ///Spotify Version: {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReportProblemClipboard {
            get {
                return ResourceManager.GetString("ReportProblemClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please leave a comment clearly describing your problem.
        ///
        ///Paste this information (already copied to your clipboard):
        ///SpotifyAdsBlocker Version: {0}
        ///Spotify Version: {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReportProblemMessageBox {
            get {
                return ResourceManager.GetString("ReportProblemMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Spotify with SpotifyAdsBlocker benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SpotifyCheckboxText {
            get {
                return ResourceManager.GetString("SpotifyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify is not installed or you have the Windows Store version.
        ///
        ///Click &apos;OK&apos; to install the normal desktop version of Spotify. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SpotifyNotFoundMessageBox {
            get {
                return ResourceManager.GetString("SpotifyNotFoundMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start SpotifyAdsBlocker on Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StartupCheckboxText {
            get {
                return ResourceManager.GetString("StartupCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusLabelLoadingText {
            get {
                return ResourceManager.GetString("StatusLabelLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Muting: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusMuting {
            get {
                return ResourceManager.GetString("StatusMuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify not found benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spotify is paused benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StatusPlaying {
            get {
                return ResourceManager.GetString("StatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolStripExit {
            get {
                return ResourceManager.GetString("ToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show SpotifyAdsBlocker Window benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolStripOpen {
            get {
                return ResourceManager.GetString("ToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove SpotifyAdsBlocker from Spotify benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolStripRemovePatch {
            get {
                return ResourceManager.GetString("ToolStripRemovePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open SpotifyAdsBlocker Website benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ToolStripWebsite {
            get {
                return ResourceManager.GetString("ToolStripWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translated by Eric Zhang benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TranslatedByText {
            get {
                return ResourceManager.GetString("TranslatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to remove SpotifyAdsBlocker from Spotify. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UndoPatchFailMessageBox {
            get {
                return ResourceManager.GetString("UndoPatchFailMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SpotifyAdsBlocker removed from Spotify. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UndoPatchOKMessageBox {
            get {
                return ResourceManager.GetString("UndoPatchOKMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error checking for update. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpgradeErrorMessageBox {
            get {
                return ResourceManager.GetString("UpgradeErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a newer version of SpotifyAdsBlocker available. Would you like to upgrade? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string UpgradeMessageBox {
            get {
                return ResourceManager.GetString("UpgradeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Volume Control benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VolumeMixerButtonText {
            get {
                return ResourceManager.GetString("VolumeMixerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open Volume Control benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string VolumeMixerOpenError {
            get {
                return ResourceManager.GetString("VolumeMixerOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report Problem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string WebsiteLinkText {
            get {
                return ResourceManager.GetString("WebsiteLinkText", resourceCulture);
            }
        }
    }
}
